// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSWCoy9t1EpNUmANQMRilAIHWsF89lNg0',
    appId: '1:1020346952071:web:941fb85000ad4b76c50b22',
    messagingSenderId: '1020346952071',
    projectId: 'sem-project-14',
    authDomain: 'sem-project-14.firebaseapp.com',
    storageBucket: 'sem-project-14.firebasestorage.app',
    measurementId: 'G-P2RJV0TK6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGR9iC4uguOb0-bh20ca2c_0xtYLYVzsM',
    appId: '1:1020346952071:android:ebafc6d40d6f2f39c50b22',
    messagingSenderId: '1020346952071',
    projectId: 'sem-project-14',
    storageBucket: 'sem-project-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXveAFYgnDeL9-2TdNFBbwR2bedLL7g3I',
    appId: '1:1020346952071:ios:7547d390bdc34cf4c50b22',
    messagingSenderId: '1020346952071',
    projectId: 'sem-project-14',
    storageBucket: 'sem-project-14.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXveAFYgnDeL9-2TdNFBbwR2bedLL7g3I',
    appId: '1:1020346952071:ios:7547d390bdc34cf4c50b22',
    messagingSenderId: '1020346952071',
    projectId: 'sem-project-14',
    storageBucket: 'sem-project-14.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSWCoy9t1EpNUmANQMRilAIHWsF89lNg0',
    appId: '1:1020346952071:web:3d7c0c9b69f1c7c1c50b22',
    messagingSenderId: '1020346952071',
    projectId: 'sem-project-14',
    authDomain: 'sem-project-14.firebaseapp.com',
    storageBucket: 'sem-project-14.firebasestorage.app',
    measurementId: 'G-EXWSTZ91ZZ',
  );
}
